# Generated by Django 5.0.1 on 2024-09-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_alter_wordoption_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordoption',
            unique_together={('word', 'option')},
        ),
    ]
