# Generated by Django 5.0.1 on 2024-12-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_alter_wordoption_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
