# Generated by Django 5.0.1 on 2024-12-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_word_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('global', 'Global'), ('private', 'Private'), ('general', 'General')], default='private', max_length=255),
        ),
    ]
