# Generated by Django 5.0.1 on 2024-12-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0007_remove_category_type_category_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercategory',
            name='category',
        ),
        migrations.AddField(
            model_name='usercategory',
            name='category',
            field=models.ManyToManyField(to='botapp.category'),
        ),
    ]
