# Generated by Django 5.0.1 on 2024-12-15 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0008_remove_usercategory_category_usercategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='botapp.botusers'),
        ),
    ]
